#cloud-config
write_files:
- path: /tmp/write_files/a.txt
  content: a
- path: /tmp/write_files/a.txt
  append: true
  permissions: '0400'
  content: b
- path: /tmp/write_files/400
  permissions: '0400'
  content: permissions 0400
- path: /tmp/write_files/root-adm
  owner: root:adm
  permissions: '0660'
  content: root:adm
